name: CMake

on:
  push:
    branches: [ timp ]
    tags: -"v*0.*"
          
  pull_request:
    branches: [ timp ]

env:
  
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      # Build your program with the given configuration
      run: cmake -H. -B_build -DCPACK_GENERATOR="TGZ" && cmake --build _build --target package &&
           cd _build && mkdir ../artifacts && 
           mv *.tar.gz ../artifacts/ 
           
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: artifacts/
        
